/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package porto2;

/**
 *
 * @author newton
 */
public class ComandanteJPanel extends javax.swing.JPanel {

    private ComandanteDAO dao = new ComandanteDAOImpl();
    
    /**
     * Creates new form ComandanteJPanel
     */
    public ComandanteJPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        nomejTextField = new javax.swing.JTextField();
        cpfjTextField = new javax.swing.JTextField();
        rgjTextField = new javax.swing.JTextField();
        nascimentojTextField = new javax.swing.JTextField();
        telefonejTextField = new javax.swing.JTextField();
        telEmergenciajTextField = new javax.swing.JTextField();
        sexojTextField = new javax.swing.JTextField();
        ruajTextField = new javax.swing.JTextField();
        bairrojTextField = new javax.swing.JTextField();
        cepjTextField = new javax.swing.JTextField();
        estadojTextField = new javax.swing.JTextField();
        cidadejTextField = new javax.swing.JTextField();
        numerojTextField = new javax.swing.JTextField();
        complementojTextField = new javax.swing.JTextField();
        registrojTextField = new javax.swing.JTextField();
        nomejLabel = new javax.swing.JLabel();
        cpfjLabel = new javax.swing.JLabel();
        rgjLabel = new javax.swing.JLabel();
        nascimentojLabel = new javax.swing.JLabel();
        telefonejLabel = new javax.swing.JLabel();
        telEmergenciajLabel = new javax.swing.JLabel();
        sexojLabel = new javax.swing.JLabel();
        ruajLabel = new javax.swing.JLabel();
        bairrojLabel = new javax.swing.JLabel();
        cepjLabel = new javax.swing.JLabel();
        estadojLabel = new javax.swing.JLabel();
        cidadejLabel = new javax.swing.JLabel();
        numerojLabel = new javax.swing.JLabel();
        complementojLabel = new javax.swing.JLabel();
        registrojLabel = new javax.swing.JLabel();
        cadastrarjButton = new javax.swing.JButton();
        limparjButton = new javax.swing.JButton();
        funcaojLabel = new javax.swing.JLabel();
        funcaojTextField = new javax.swing.JTextField();

        setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Comandante", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 0, 18))); // NOI18N

        nomejLabel.setText("Nome:");

        cpfjLabel.setText("CPF:");

        rgjLabel.setText("RG:");

        nascimentojLabel.setText("Nascimento:");

        telefonejLabel.setText("Telefone:");

        telEmergenciajLabel.setText("Tel. Emergência:");

        sexojLabel.setText("Sexo:");

        ruajLabel.setText("Rua:");

        bairrojLabel.setText("Bairro:");

        cepjLabel.setText("CEP:");

        estadojLabel.setText("Estado:");

        cidadejLabel.setText("Cidade:");

        numerojLabel.setText("Número:");

        complementojLabel.setText("Complemento:");

        registrojLabel.setText("Registro:");

        cadastrarjButton.setText("Cadastrar");
        cadastrarjButton.setMaximumSize(new java.awt.Dimension(100, 30));
        cadastrarjButton.setMinimumSize(new java.awt.Dimension(100, 30));
        cadastrarjButton.setPreferredSize(new java.awt.Dimension(100, 30));
        cadastrarjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastrarjButtonActionPerformed(evt);
            }
        });

        limparjButton.setText("Limpar");
        limparjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                limparjButtonActionPerformed(evt);
            }
        });

        funcaojLabel.setText("Função:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(funcaojLabel)
                    .addComponent(nomejLabel)
                    .addComponent(cpfjLabel)
                    .addComponent(rgjLabel)
                    .addComponent(nascimentojLabel)
                    .addComponent(telefonejLabel)
                    .addComponent(sexojLabel)
                    .addComponent(ruajLabel)
                    .addComponent(bairrojLabel)
                    .addComponent(cepjLabel)
                    .addComponent(estadojLabel)
                    .addComponent(telEmergenciajLabel)
                    .addComponent(cidadejLabel)
                    .addComponent(numerojLabel)
                    .addComponent(complementojLabel)
                    .addComponent(registrojLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(cadastrarjButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(limparjButton, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(rgjTextField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 694, Short.MAX_VALUE)
                    .addComponent(nascimentojTextField, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(telefonejTextField, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(sexojTextField, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(ruajTextField, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(bairrojTextField, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(cepjTextField, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(estadojTextField, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(telEmergenciajTextField)
                    .addComponent(cidadejTextField)
                    .addComponent(numerojTextField)
                    .addComponent(complementojTextField)
                    .addComponent(registrojTextField)
                    .addComponent(funcaojTextField)
                    .addComponent(cpfjTextField)
                    .addComponent(nomejTextField)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nomejTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nomejLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cpfjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cpfjLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rgjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rgjLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nascimentojTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nascimentojLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(telefonejTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(telefonejLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(telEmergenciajTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(telEmergenciajLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sexojTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sexojLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ruajTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ruajLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bairrojTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bairrojLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cepjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cepjLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(estadojTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(estadojLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cidadejTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cidadejLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(numerojTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(numerojLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(complementojTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(complementojLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(registrojTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(registrojLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(funcaojTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(funcaojLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cadastrarjButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(limparjButton))
                .addContainerGap(38, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void limparjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_limparjButtonActionPerformed
        // TODO add your handling code here:
        nomejTextField.setText("");
        cpfjTextField.setText("");
        rgjTextField.setText("");
        nascimentojTextField.setText("");
        telefonejTextField.setText("");
        telEmergenciajTextField.setText("");
        sexojTextField.setText("");
        ruajTextField.setText("");
        bairrojTextField.setText("");
        cepjTextField.setText("");
        estadojTextField.setText("");
        cidadejTextField.setText("");
        numerojTextField.setText("");
        complementojTextField.setText("");
        registrojTextField.setText("");
        funcaojTextField.setText("");
    }//GEN-LAST:event_limparjButtonActionPerformed

    private void cadastrarjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastrarjButtonActionPerformed
        // TODO add your handling code here:
        Comandante novo = new Comandante();
        novo.setCpf(cpfjTextField.getText());
        novo.setNome(nomejTextField.getText());
        novo.setRg(rgjTextField.getText());
        novo.setTelefone(telefonejTextField.getText());
        novo.setRegistro(registrojTextField.getText());
        novo.setFuncao(funcaojTextField.getText());
        
        Endereco end = new Endereco();
        end.setBairro(bairrojTextField.getText());
        end.setCep(cepjTextField.getText());
        end.setCidade(cidadejTextField.getText());
        end.setComplemento(complementojTextField.getText());
        end.setEstado(estadojTextField.getText());
        end.setNumero(numerojTextField.getText());
        end.setRua(ruajTextField.getText());

        novo.setEndereco(end);

        
        dao.inserir(novo);
        limparjButtonActionPerformed(null);
    }//GEN-LAST:event_cadastrarjButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bairrojLabel;
    private javax.swing.JTextField bairrojTextField;
    private javax.swing.JButton cadastrarjButton;
    private javax.swing.JLabel cepjLabel;
    private javax.swing.JTextField cepjTextField;
    private javax.swing.JLabel cidadejLabel;
    private javax.swing.JTextField cidadejTextField;
    private javax.swing.JLabel complementojLabel;
    private javax.swing.JTextField complementojTextField;
    private javax.swing.JLabel cpfjLabel;
    private javax.swing.JTextField cpfjTextField;
    private javax.swing.JLabel estadojLabel;
    private javax.swing.JTextField estadojTextField;
    private javax.swing.JLabel funcaojLabel;
    private javax.swing.JTextField funcaojTextField;
    private javax.swing.JButton limparjButton;
    private javax.swing.JLabel nascimentojLabel;
    private javax.swing.JTextField nascimentojTextField;
    private javax.swing.JLabel nomejLabel;
    private javax.swing.JTextField nomejTextField;
    private javax.swing.JLabel numerojLabel;
    private javax.swing.JTextField numerojTextField;
    private javax.swing.JLabel registrojLabel;
    private javax.swing.JTextField registrojTextField;
    private javax.swing.JLabel rgjLabel;
    private javax.swing.JTextField rgjTextField;
    private javax.swing.JLabel ruajLabel;
    private javax.swing.JTextField ruajTextField;
    private javax.swing.JLabel sexojLabel;
    private javax.swing.JTextField sexojTextField;
    private javax.swing.JLabel telEmergenciajLabel;
    private javax.swing.JTextField telEmergenciajTextField;
    private javax.swing.JLabel telefonejLabel;
    private javax.swing.JTextField telefonejTextField;
    // End of variables declaration//GEN-END:variables
}
