/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package porto2;

import javax.swing.JPanel;

/**
 *
 * @author newton
 */
public class PrincipalJFrame extends javax.swing.JFrame {

    /**
     * Creates new form PrincipalJFrame
     */
    public PrincipalJFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        comandanteJMenu = new javax.swing.JMenu();
        comandantejMenuItem = new javax.swing.JMenuItem();
        passageiroJMenu = new javax.swing.JMenu();
        passageirojMenuItem = new javax.swing.JMenuItem();
        funcionarioJMenu = new javax.swing.JMenu();
        funcionariojMenuItem = new javax.swing.JMenuItem();
        bagagemjMenu = new javax.swing.JMenu();
        bagagemjMenuItem = new javax.swing.JMenuItem();
        embarcacaojMenu = new javax.swing.JMenu();
        embarcacaojMenuItem = new javax.swing.JMenuItem();
        empresajMenu = new javax.swing.JMenu();
        empresajMenuItem = new javax.swing.JMenuItem();
        almoxarifadojMenu = new javax.swing.JMenu();
        entradaprodutosjMenuItem = new javax.swing.JMenuItem();
        localjMenu = new javax.swing.JMenu();
        localjMenuItem = new javax.swing.JMenuItem();
        produtojMenu = new javax.swing.JMenu();
        produtojMenuItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new javax.swing.BoxLayout(jPanel1, javax.swing.BoxLayout.LINE_AXIS));

        comandanteJMenu.setText("Comandante");

        comandantejMenuItem.setText("Comandante");
        comandantejMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comandantejMenuItemActionPerformed(evt);
            }
        });
        comandanteJMenu.add(comandantejMenuItem);

        jMenuBar1.add(comandanteJMenu);

        passageiroJMenu.setText("Passageiro");

        passageirojMenuItem.setText("Passageiro");
        passageirojMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passageirojMenuItemActionPerformed(evt);
            }
        });
        passageiroJMenu.add(passageirojMenuItem);

        jMenuBar1.add(passageiroJMenu);

        funcionarioJMenu.setText("Funcionário");

        funcionariojMenuItem.setText("Funcionário");
        funcionariojMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                funcionariojMenuItemActionPerformed(evt);
            }
        });
        funcionarioJMenu.add(funcionariojMenuItem);

        jMenuBar1.add(funcionarioJMenu);

        bagagemjMenu.setText("Bagagem");

        bagagemjMenuItem.setText("Bagagem");
        bagagemjMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bagagemjMenuItemActionPerformed(evt);
            }
        });
        bagagemjMenu.add(bagagemjMenuItem);

        jMenuBar1.add(bagagemjMenu);

        embarcacaojMenu.setText("Embarcação");

        embarcacaojMenuItem.setText("Embarcação");
        embarcacaojMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                embarcacaojMenuItemActionPerformed(evt);
            }
        });
        embarcacaojMenu.add(embarcacaojMenuItem);

        jMenuBar1.add(embarcacaojMenu);

        empresajMenu.setText("Empresa");

        empresajMenuItem.setText("Empresa");
        empresajMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                empresajMenuItemActionPerformed(evt);
            }
        });
        empresajMenu.add(empresajMenuItem);

        jMenuBar1.add(empresajMenu);

        almoxarifadojMenu.setText("Almoxarifado");

        entradaprodutosjMenuItem.setText("Entrada de Produtos");
        entradaprodutosjMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                entradaprodutosjMenuItemActionPerformed(evt);
            }
        });
        almoxarifadojMenu.add(entradaprodutosjMenuItem);

        jMenuBar1.add(almoxarifadojMenu);

        localjMenu.setText("Local");

        localjMenuItem.setText("Local");
        localjMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                localjMenuItemActionPerformed(evt);
            }
        });
        localjMenu.add(localjMenuItem);

        jMenuBar1.add(localjMenu);

        produtojMenu.setText("Produto");

        produtojMenuItem.setText("Produto");
        produtojMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                produtojMenuItemActionPerformed(evt);
            }
        });
        produtojMenu.add(produtojMenuItem);

        jMenuBar1.add(produtojMenu);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 841, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 587, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void localjMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_localjMenuItemActionPerformed
        // TODO add your handling code here:
        setConteudo(new LocalJPanel());
    }//GEN-LAST:event_localjMenuItemActionPerformed

    private void comandantejMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comandantejMenuItemActionPerformed
        // TODO add your handling code here:
        setConteudo(new ComandanteJPanel());
    }//GEN-LAST:event_comandantejMenuItemActionPerformed

    private void passageirojMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passageirojMenuItemActionPerformed
        // TODO add your handling code here:
        setConteudo(new PassageiroJPanel());
    }//GEN-LAST:event_passageirojMenuItemActionPerformed

    private void funcionariojMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_funcionariojMenuItemActionPerformed
        // TODO add your handling code here:
        setConteudo(new FuncionarioJPanel());
    }//GEN-LAST:event_funcionariojMenuItemActionPerformed

    private void bagagemjMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bagagemjMenuItemActionPerformed
        // TODO add your handling code here:
        setConteudo(new BagagemJPanel());
    }//GEN-LAST:event_bagagemjMenuItemActionPerformed

    private void embarcacaojMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_embarcacaojMenuItemActionPerformed
        // TODO add your handling code here:
        setConteudo(new EmbarcacaoJPanel());
    }//GEN-LAST:event_embarcacaojMenuItemActionPerformed

    private void empresajMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_empresajMenuItemActionPerformed
        // TODO add your handling code here:
        setConteudo(new EmpresaJPanel());
    }//GEN-LAST:event_empresajMenuItemActionPerformed

    private void entradaprodutosjMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_entradaprodutosjMenuItemActionPerformed
        // TODO add your handling code here:
        setConteudo(new EntradaProdutoJPanel());
    }//GEN-LAST:event_entradaprodutosjMenuItemActionPerformed

    private void produtojMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_produtojMenuItemActionPerformed
        // TODO add your handling code here:
        setConteudo(new ProdutoJPanel());
    }//GEN-LAST:event_produtojMenuItemActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PrincipalJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PrincipalJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PrincipalJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PrincipalJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PrincipalJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu almoxarifadojMenu;
    private javax.swing.JMenu bagagemjMenu;
    private javax.swing.JMenuItem bagagemjMenuItem;
    private javax.swing.JMenu comandanteJMenu;
    private javax.swing.JMenuItem comandantejMenuItem;
    private javax.swing.JMenu embarcacaojMenu;
    private javax.swing.JMenuItem embarcacaojMenuItem;
    private javax.swing.JMenu empresajMenu;
    private javax.swing.JMenuItem empresajMenuItem;
    private javax.swing.JMenuItem entradaprodutosjMenuItem;
    private javax.swing.JMenu funcionarioJMenu;
    private javax.swing.JMenuItem funcionariojMenuItem;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JMenu localjMenu;
    private javax.swing.JMenuItem localjMenuItem;
    private javax.swing.JMenu passageiroJMenu;
    private javax.swing.JMenuItem passageirojMenuItem;
    private javax.swing.JMenu produtojMenu;
    private javax.swing.JMenuItem produtojMenuItem;
    // End of variables declaration//GEN-END:variables

    private void setConteudo(JPanel tela) {
        jPanel1.removeAll();
        jPanel1.add(tela);
        jPanel1.setVisible(false);
        jPanel1.setVisible(true);
    }
}
